export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const REMOVE_DONE_TODO = 'REMOVE_DONE_TODO';

export const REQUEST_TODOS_PENDING = 'REQUEST_TODOS_PENDING';
export const REQUEST_TODOS_SUCCESS = 'REQUEST_TODOS_SUCCESS';
export const REQUEST_TODOS_FAILED = 'REQUEST_TODOS_FAILED';

export const ADD_TODO_PENDING = 'ADD_TODO_PENDING';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED';

export const REMOVE_TODO_PENDING = 'REMOVE_TODO_PENDING';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_FAILED = 'REMOVE_TODO_FAILED';

export const REMOVE_DONE_TODO_PENDING = 'REMOVE_DONE_TODO_PENDING';
export const REMOVE_DONE_TODO_SUCCESS = 'REMOVE_DONE_TODO_SUCCESS';
export const REMOVE_DONE_TODO_FAILED = 'REMOVE_DONE_TODO_FAILED';
